---
author: admin
categories:
- Java
- 技術メモ
date: 2015-01-15T15:07:00+00:00
dsq_thread_id:
- 3.6960274e+09
excerpt: Java の例外処理について徹底的に調べてみた
pvc_views:
- 26377
title: Java の例外処理について徹底的に調べてみた
type: post
url: /archives/=2935
---

[<img alt="" src="http://futurismo.biz/wp-content/uploads/java.png" width="256" height="256" />][1]

<div id="outline-container-unnumbered-1" class="outline-2">
  <h2 id="unnumbered-1">
    はじめに
  </h2>
  
  <div class="outline-text-2" id="text-unnumbered-1">
    <p>
      Java 言語で開発をしていて, 例外処理をよく知らないため調べてみた.
    </p>
    
    <p>
      自分が仕事で関わっている製品は, (異常なくらい?) 高品質と高信頼性が求められているにも関わらず, 開発者がへなちょこだと, 安心してみんな銀行にお金をあずけられないからね.
    </p>
  </div>
</div>

<div id="outline-container-unnumbered-2" class="outline-2">
  <h2 id="unnumbered-2">
    例外処理 (Exceptions) とは
  </h2>
  
  <div class="outline-text-2" id="text-unnumbered-2">
    <p>
      そもそも例外処理はなにかを Wikipedia から調べてみる.
    </p>
    
    <ul class="org-ul">
      <li>
        <a href="http://ja.wikipedia.org/wiki/%E4%BE%8B%E5%A4%96%E5%87%A6%E7%90%86">例外処理 &#8211; Wikipedia</a>
      </li>
    </ul>
    
    <p>
      例外処理とは,
    </p>
    
    <blockquote>
      <p>
        プログラムがある処理を実行している途中で, なんらかの異常が発生した場合に, 現在の処理を中断 (中止) して, 別の処理を行うこと.
      </p>
    </blockquote>
  </div>
  
  <div id="outline-container-unnumbered-3" class="outline-3">
    <h3 id="unnumbered-3">
      言語サポートについて
    </h3>
    
    <div class="outline-text-3" id="text-unnumbered-3">
      <blockquote>
        <p>
          幾つかのプログラミング言語では組み込みの例外処理機能を用意している.
        </p>
      </blockquote>
      
      <p>
        言語のサポートがないものとして自分が知っているのは, C 言語.
      </p>
      
      <p>
        以前 C 言語 & vxWorks で開発していたときは, 致命的なエラーが発生したら kernel の関数をコールすることで, システムを緊急停止するようなことをしていた.
      </p>
      
      <p>
        ここでのポイントは, 例外とはプログラミング技術の一つで, すべての言語に応用できるということ.
      </p>
      
      <p>
        この言語では, 例外処理をどうやってサポートしていて, それが Java とはどう違うのかまで考えられるようになりたい.
      </p>
    </div>
  </div>
  
  <div id="outline-container-unnumbered-4" class="outline-3">
    <h3 id="unnumbered-4">
      CTMCP からの引用
    </h3>
    
    <div class="outline-text-3" id="text-unnumbered-4">
      <ul class="org-ul">
        <li>
          try ・・・ 例外ハンドラをもつ例外補足コンテクストを生成.
        </li>
        <li>
          raise ・・・ もっとも内部の例外補足コンテキストへ jamp し, そこにある例外ハンドラを起動.
        </li>
      </ul>
      
      <p>
        各コンテキストはスタックで管理され, try はスタックの 1 つに marker をつける. raise は marker にジャンプして marker の場所に例外処理のコンテキストを挿入する.
      </p>
      
      <p>
        CTM p93 参照.
      </p>
    </div>
  </div>
  
  <div id="outline-container-unnumbered-5" class="outline-3">
    <h3 id="unnumbered-5">
      例外の種類
    </h3>
    
    <div class="outline-text-3" id="text-unnumbered-5">
      <ul class="org-ul">
        <li>
          Asynchronous Exceptions: 非同期例外
        </li>
        <li>
          Synchronous Exceptions: 同期例外 <ul class="org-ul">
            <li>
              Traps: 意図的に OS が止める breakpont, systemcall, file open
            </li>
            <li>
              Faults: リカバリ可能な例外, page fault, segmentation fault
            </li>
            <li>
              Aborts: リカバリ不可能な例外, プログラムは強制終了.
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  
  <div id="outline-container-unnumbered-6" class="outline-3">
    <h3 id="unnumbered-6">
      例外がないと困ること
    </h3>
    
    <div class="outline-text-3" id="text-unnumbered-6">
      <p>
        例外をつかわないと, コンテクストごとの結果を検証必要があり, return 文 と case 文が乱立するうんこうんこコードが出来る.
      </p>
      
      <p>
        例えば, 下位のコンテキスト (A) で発生したエラーは, return -> return -> して上位でも戻り値のエラーチェックが必要.
      </p>
      
      <p>
        C だど, メモリ獲得できたかの null チェックをよくする.
      </p>
      
      <p>
        [sourcecode language=&#8221;c&#8221; title=&#8221;&#8221; ]<br /> #define ERROR -1<br /> #define OK 0
      </p>
      
      <p>
        int main (void) {<br /> if (C ()==ERROR) {<br /> printf (&#8220;Error\n&#8221;);<br /> }<br /> }
      </p>
      
      <p>
        int A () {<br /> return ERROR;<br /> }
      </p>
      
      <p>
        int B () {<br /> int ret = A ();
      </p>
      
      <p>
        if (ret == ERROR) {<br /> return ERROR;<br /> }<br /> else {<br /> return OK;<br /> }<br /> }
      </p>
      
      <p>
        int C () {<br /> int ret = B ();
      </p>
      
      <p>
        if (ret == ERROR) {<br /> return ERROR;<br /> }<br /> else {<br /> return OK;<br /> }<br /> }<br /> [/sourcecode]
      </p>
      
      <p>
        Java ならば, return 文のチェックをする必要がない.
      </p>
      
      <p>
        [sourcecode language=&#8221;java&#8221; title=&#8221;&#8221; ]<br /> public class ExceptionSample {<br /> static final int ERROR = -1;<br /> static final int OK = 0;
      </p>
      
      <p>
        public static void main (String args[]) {<br /> try {<br /> C ();<br /> }<br /> catch (Throwable e) {<br /> e.printStackTrace ();<br /> }<br /> }
      </p>
      
      <p>
        public int A () {<br /> throw new RuntimeException (&#8220;上位のメソッドへ一気にジャ~ンプ (￣, ￣) 丿&#8221;);<br /> return OK;<br /> }
      </p>
      
      <p>
        public int B () {<br /> A ();<br /> return OK;<br /> }
      </p>
      
      <p>
        public int C () {<br /> B ();<br /> return OK;<br /> }<br /> }<br /> [/sourcecode]
      </p>
    </div>
  </div>
</div>

<div id="outline-container-unnumbered-7" class="outline-2">
  <h2 id="unnumbered-7">
    Java での例外
  </h2>
  
  <div class="outline-text-2" id="text-unnumbered-7">
    <p>
      Java では例外はクラスとして実装する.
    </p>
  </div>
  
  <div id="outline-container-unnumbered-8" class="outline-3">
    <h3 id="unnumbered-8">
      文法
    </h3>
    
    <div class="outline-text-3" id="text-unnumbered-8">
    </div>
    
    <div id="outline-container-unnumbered-9" class="outline-4">
      <h4 id="unnumbered-9">
        try
      </h4>
      
      <div class="outline-text-4" id="text-unnumbered-9">
        <p>
          例外を捕まえるための範囲 (コンテキスト) を作る. {}で囲まれた部分がコンテキストになる.
        </p>
      </div>
    </div>
    
    <div id="outline-container-unnumbered-10" class="outline-4">
      <h4 id="unnumbered-10">
        catch
      </h4>
      
      <div class="outline-text-4" id="text-unnumbered-10">
        <p>
          try{}で作成したコンテキスト内で発生した例外を捕まえたあとに 処理する内容を書く. エラーログを吐くとか.
        </p>
      </div>
    </div>
    
    <div id="outline-container-unnumbered-11" class="outline-4">
      <h4 id="unnumbered-11">
        finally
      </h4>
      
      <div class="outline-text-4" id="text-unnumbered-11">
        <p>
          最後にかならず実施したい処理を書く.
        </p>
        
        <p>
          例えば IO ファイルを Open して処理している途中で異常が発生したとき, ファイルを閉じる処理など.
        </p>
      </div>
    </div>
    
    <div id="outline-container-unnumbered-12" class="outline-4">
      <h4 id="unnumbered-12">
        try と catch の例
      </h4>
      
      <div class="outline-text-4" id="text-unnumbered-12">
        <p>
          try 文には正常系を, catch 文には異常系を書く.
        </p>
        
        <p>
          こうすることで,
        </p>
        
        <p>
          <b>正常系のコードと異常系のコードを明確に分ける</b>
        </p>
        
        <p>
          ことができる (そして, 異常系は後回し&#x2026;)
        </p>
        
        <p>
          [sourcecode language=&#8221;java&#8221; title=&#8221;&#8221; ]<br /> try {<br /> hoge ()<br /> } catch (FooException e1) { // 例外クラス 変数名<br /> e1.printStackTrace ();<br /> } catch (BarException e2) { // 例外クラス 変数名<br /> e2.printStackTrace ();<br /> } finally {<br /> // 任意<br /> }<br /> [/sourcecode]
        </p>
        
        <p>
          printStackTrace () メソッドを書くと, 例外発生時のスタックトレースを表示できる.
        </p>
      </div>
    </div>
    
    <div id="outline-container-unnumbered-13" class="outline-4">
      <h4 id="unnumbered-13">
        throw
      </h4>
      
      <div class="outline-text-4" id="text-unnumbered-13">
        <p>
          throw 文をつかうと, 自分で例外を投げることができる. 引数にメッセージをわたすこともできる.
        </p>
        
        <p>
          [sourcecode language=&#8221;java&#8221; title=&#8221;&#8221; ]<br /> throw new HogeException (&#8220;秘密のメッセージ&#8221;);<br /> [/sourcecode]
        </p>
      </div>
    </div>
  </div>
  
  <div id="outline-container-unnumbered-14" class="outline-3">
    <h3 id="unnumbered-14">
      例外の種類
    </h3>
    
    <div class="outline-text-3" id="text-unnumbered-14">
      <p>
        Throwable クラスを継承するかたちで, 各例外クラスが定義されている. 以下のようなサブクラスで小分類されている.
      </p>
      
      <table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
        <colgroup> <col class="left" /> <col class="left" /> <col class="left" /> </colgroup> <tr>
          <td>
            Error
          </td>
          
          <td>
            &#xa0;
          </td>
          
          <td>
            処理の継続不可. 致命的なエラー.
          </td>
        </tr>
        
        <tr>
          <td>
            Exception
          </td>
          
          <td>
            検査例外
          </td>
          
          <td>
            コンパイル時に例外処理の実装が強制される
          </td>
        </tr>
        
        <tr>
          <td>
            RuntimeException
          </td>
          
          <td>
            実行時例外
          </td>
          
          <td>
            コンパイル時に例外処理の実装が強制されません.
          </td>
        </tr>
      </table>
    </div>
  </div>
  
  <div id="outline-container-unnumbered-15" class="outline-3">
    <h3 id="unnumbered-15">
      独自定義の例外
    </h3>
    
    <div class="outline-text-3" id="text-unnumbered-15">
      <p>
        Java の例外はクラスなので, 上のクラスを継承したクラスを定義することで, 独自例外を作成できる.
      </p>
      
      <p>
        Error と RuntimeException は, Java 仮想マシンが通知してくる特別な 例外なので, 一般のプログラマは, 以下のどちらかで定義.
      </p>
      
      <ul class="org-ul">
        <li>
          Java API で用意されている Exception のサブクラスを使う
        </li>
        <li>
          <p>
            java.lang.Exception Exception のサブクラスを自分で定義する
          </p>
          
          <p>
            [sourcecode language=&#8221;java&#8221; title=&#8221;&#8221; ]<br /> class MyException extends Exception {}<br /> [/sourcecode]</li> </ul> 
            
            <p>
              こんな風にかけば, 上位のコンテキストにエラーコードを渡すことができ る. catch ブロックで発生したエラーによって, 処理を分岐できる.
            </p>
            
            <p>
              しかし, 分岐するならば, 例外クラスを定義した方がエレガントだ.
            </p>
            
            <p>
              [sourcecode language=&#8221;java&#8221; title=&#8221;&#8221; ]<br /> import java.lang.Exception;<br /> public class MyErrorSample {<br /> public static void main (String args[]) {<br /> try {<br /> throw new MyException (5);<br /> }<br /> catch (MyException e) {<br /> e.printStackTrace ();<br /> System.out.println (&#8220;ErrorCode = &#8221; + e.getCode ());<br /> }<br /> }<br /> }
            </p>
            
            <p>
              class MyException extends Exception {<br /> int errorCode;
            </p>
            
            <p>
              MyException (int errorCode) {<br /> this.errorCode = errorCode;<br /> }
            </p>
            
            <p>
              int getCode () {<br /> return errorCode;<br /> }<br /> }<br /> [/sourcecode]
            </p>
            
            <p>
              [sourcecode language=&#8221;text&#8221; title=&#8221;&#8221; ]<br /> ErrorCode = 5<br /> [/sourcecode]
            </p></div> 
            
            <div id="outline-container-unnumbered-16" class="outline-4">
              <h4 id="unnumbered-16">
                Eclipse
              </h4>
              
              <div class="outline-text-4" id="text-unnumbered-16">
                <p>
                  Eclipse では, カスタム例外を作成するための機能がついてる. 簡単に作成できる.
                </p>
                
                <ul class="org-ul">
                  <li>
                    <a href="http://www.atmarkit.co.jp/ait/articles/1112/20/news131.html">【改訂版】 Eclipse ではじめるプログラミング (24):Java の例外処理で知らないと損する 7 つのテクニック (1/3) &#8211; ＠ IT</a>
                  </li>
                </ul>
              </div>
            </div></div> 
            
            <div id="outline-container-unnumbered-17" class="outline-3">
              <h3 id="unnumbered-17">
                Java の標準的な例外クラス
              </h3>
              
              <div class="outline-text-3" id="text-unnumbered-17">
                <p>
                  そもそも, この記事を書こうと思ったのは, 例外処理をしたいとき, なにを throw すればいいのかわからなかったから.
                </p>
                
                <p>
                  Effective Java にも, 標準例外を利用するようにと書いてある.
                </p>
                
                <ul class="org-ul">
                  <li>
                    みんな知っているから
                  </li>
                  <li>
                    パフォーマンスが軽くなるから
                  </li>
                </ul>
                
                <p>
                  標準的に利用される Java の例外を以下にまとめてみる. このくらいならば, 簡単に覚えて使いこなせそうだ.
                </p>
                
                <table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
                  <colgroup> <col class="left" /> <col class="left" /> <col class="left" /> </colgroup> <tr>
                    <th scope="col">
                      Definition
                    </th>
                    
                    <th scope="col">
                      Description
                    </th>
                    
                    <th scope="col">
                      Example
                    </th>
                  </tr>
                  
                  <tr>
                    <td>
                      java.lang.IllegalArgumentException
                    </td>
                    
                    <td>
                      不適切な引数
                    </td>
                    
                    <td>
                      パラメータエラー
                    </td>
                  </tr>
                  
                  <tr>
                    <td>
                      java.lang.IllegalStateException
                    </td>
                    
                    <td>
                      不正な状態
                    </td>
                    
                    <td>
                      未初期化で呼び出し
                    </td>
                  </tr>
                  
                  <tr>
                    <td>
                      java.lang.NullPointerException.
                    </td>
                    
                    <td>
                      Null アクセス
                    </td>
                    
                    <td>
                      &#xa0;
                    </td>
                  </tr>
                  
                  <tr>
                    <td>
                      java.lang.IndexOutOfBoundsException
                    </td>
                    
                    <td>
                      範囲外
                    </td>
                    
                    <td>
                      配列の Index オーバ
                    </td>
                  </tr>
                  
                  <tr>
                    <td>
                      java.util.ConcurrentMdificationException
                    </td>
                    
                    <td>
                      マルチスレッドアクセス
                    </td>
                    
                    <td>
                      平行処理漏れ
                    </td>
                  </tr>
                  
                  <tr>
                    <td>
                      java.lang.UnsupportedOperationException
                    </td>
                    
                    <td>
                      未サポート機能
                    </td>
                    
                    <td>
                      未サポートなのにメソッドが呼ばれた
                    </td>
                  </tr>
                </table>
                
                <p>
                  自分で利用しないまでも, よくみかける例外が以下にまとまっている. デバッグの友.
                </p>
                
                <ul class="org-ul">
                  <li>
                    <a href="http://docs.oracle.com/javame/config/cdc/ref-impl/cdc1.1.2/jsr218/ja/java/lang/class-use/Exception.html">クラス java.lang.Exception の使用 (Connected Device Configuration (CDC), バージョン 1.1.2)</a>
                  </li>
                  <li>
                    <a href="http://www.ne.jp/asahi/hishidama/home/tech/java/exception.html">Java 例外メモ (Hishidama&#8217;s Java Exception Memo)</a>
                  </li>
                </ul>
              </div>
            </div></div> 
            
            <div id="outline-container-unnumbered-18" class="outline-2">
              <h2 id="unnumbered-18">
                おわりに
              </h2>
              
              <div class="outline-text-2" id="text-unnumbered-18">
                <p>
                  これで明日からも, 例外処理と戦えそうです&#x2026; はぁ.
                </p>
              </div>
            </div>
            
            <div id="outline-container-unnumbered-19" class="outline-2">
              <h2 id="unnumbered-19">
                Bookmarks
              </h2>
              
              <div class="outline-text-2" id="text-unnumbered-19">
                <ul class="org-ul">
                  <li>
                    <a href="https://moneyforward.com/engineers_blog/2014/08/22/java%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E4%BE%8B%E5%A4%96%E5%87%A6%E7%90%86%E3%81%AE%E3%83%99%E3%82%B9%E3%83%88%E3%83%BB%E3%83%97%E3%83%A9%E3%82%AF%E3%83%86%E3%82%A3%E3%82%B9/">Java における例外処理のベスト・プラクティス | マネーフォワード エンジニアブログ</a>
                  </li>
                  <li>
                    <a href="http://www.itsenka.com/contents/development/java/exception.html">例外処理 &#8211; Java 入門 &#8211; IT 専科</a>
                  </li>
                  <li>
                    <a href="http://www.ohshiro.tuis.ac.jp/~ohshiro/ooprog_b/04/">オブジェクト指向プログラミング b 第 4 回</a>
                  </li>
                  <li>
                    <a href="http://d.hatena.ne.jp/unageanu/20070830/1188476810">「エラーの原因ごとに例外の型を別ける」のはどうなの? &#8211; うなの日記</a>
                  </li>
                </ul>
              </div>
            </div>

 [1]: http://futurismo.biz/wp-content/uploads/java.png